version: '3.8'

services:
  app:
    image: docuseal/docuseal:latest
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/docuseal
      - FORCE_SSL=true
      - HOST=mern-blogging.vrugle.com
    networks:
      - docuseal-net

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docuseal
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - docuseal-net

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "32794:3000"  # Using the already allocated port from your system
    command: ["caddy", "reverse-proxy", "--from", ":3000", "--to", "app:3000"]
    networks:
      - docuseal-net

networks:
  docuseal-net:
    driver: bridge

volumes:
  pg_data: